import React from "react";
import {
  LuLayoutDashboard,
  LuDatabase,
  LuBot,
  LuShieldCheck,
  LuActivity,
  LuChartBar,
  LuSettings,
  LuFileText,
  LuLayers,
  LuBoxes,
  LuTriangleAlert,
  LuCircleAlert,
  LuCircleCheck,
  LuCircleX,
  LuClock,
  LuUpload,
  LuRefreshCw,
  LuEye,
  LuSearch,
  LuPlay,
  LuSend,
  LuCheck,
  LuX,
  LuCopy,
  LuExternalLink,
  LuChevronRight,
  LuChevronLeft,
  LuChevronDown,
  LuChevronUp,
  LuScissors,
  LuCpu,
  LuFilter,
  LuLock,
  LuMail,
  LuUser,
  LuLogOut,
  LuSparkles,
  LuLoaderCircle,
  LuArrowRight,
  LuArrowUpRight,
  LuDownload,
  LuPlus,
  LuTrash2,
  LuShield,
  LuFileCheck,
  LuHash,
  LuBookmark,
  LuFileSpreadsheet,
  LuFileCode,
  LuKey,
  LuGlobe,
  LuDollarSign,
  LuSquare,
  LuZap,
  LuSlidersHorizontal,
} from "react-icons/lu";

export type IconProps = React.ComponentPropsWithoutRef<"svg"> & {
  size?: number | string;
};

/**
 * Standardized Application Icon Registry
 * Single unified icon source (react-icons/lu) providing consistent stroke,
 * 2px outline aesthetics, uniform visual weights, and semantic categorization.
 */
export const AppIcons = {
  // 1. Navigation / Sidebar (18–20px)
  dashboard: LuLayoutDashboard,
  corpus: LuDatabase,
  copilot: LuBot,
  reviews: LuShieldCheck,
  runs: LuActivity,
  evaluation: LuChartBar,
  settings: LuSettings,

  // 2. Primary KPI Identifiers (18–22px)
  documents: LuFileText,
  pages: LuLayers,
  chunks: LuBoxes,
  failures: LuTriangleAlert,

  // 3. 5-Stage Ingestion Pipeline (16–18px)
  extract: LuFileText,
  clean: LuFilter,
  chunk: LuScissors,
  embed: LuCpu,
  index: LuDatabase,

  // 4. Standardized Status Indicators (14–16px)
  success: LuCircleCheck,
  error: LuCircleX,
  warning: LuTriangleAlert,
  info: LuCircleAlert,
  pending: LuClock,
  loading: LuLoaderCircle,
  activity: LuActivity,

  // 5. User Actions (14–18px)
  upload: LuUpload,
  refresh: LuRefreshCw,
  inspect: LuEye,
  search: LuSearch,
  run: LuPlay,
  send: LuSend,
  stop: LuSquare,
  approve: LuCheck,
  reject: LuX,
  copy: LuCopy,
  check: LuCheck,
  close: LuX,
  filter: LuFilter,
  external: LuExternalLink,
  download: LuDownload,
  plus: LuPlus,
  delete: LuTrash2,

  // 6. Navigation Controls & Chevrons (14–18px)
  chevronRight: LuChevronRight,
  chevronLeft: LuChevronLeft,
  chevronDown: LuChevronDown,
  chevronUp: LuChevronUp,
  arrowRight: LuArrowRight,
  arrowUpRight: LuArrowUpRight,

  // 7. Security, Auth & System Context
  lock: LuLock,
  user: LuUser,
  logout: LuLogOut,
  shield: LuShield,
  shieldCheck: LuShieldCheck,
  mail: LuMail,
  key: LuKey,
  globe: LuGlobe,
  sparkles: LuSparkles,
  zap: LuZap,
  sliders: LuSlidersHorizontal,
  dollar: LuDollarSign,
  hash: LuHash,
  bookmark: LuBookmark,
  fileCheck: LuFileCheck,
  fileSpreadsheet: LuFileSpreadsheet,
  fileCode: LuFileCode,
  cpu: LuCpu,
  database: LuDatabase,
};

// Re-export individual icons for convenient named consumption
export {
  LuLayoutDashboard as IconDashboard,
  LuDatabase as IconDatabase,
  LuBot as IconBot,
  LuShieldCheck as IconShieldCheck,
  LuActivity as IconActivity,
  LuChartBar as IconChartBar,
  LuSettings as IconSettings,
  LuFileText as IconFileText,
  LuLayers as IconLayers,
  LuBoxes as IconBoxes,
  LuTriangleAlert as IconAlertTriangle,
  LuCircleAlert as IconAlertCircle,
  LuCircleCheck as IconCheckCircle,
  LuCircleX as IconXCircle,
  LuClock as IconClock,
  LuUpload as IconUpload,
  LuRefreshCw as IconRefresh,
  LuEye as IconEye,
  LuSearch as IconSearch,
  LuPlay as IconPlay,
  LuSend as IconSend,
  LuSquare as IconSquare,
  LuCheck as IconCheck,
  LuX as IconX,
  LuCopy as IconCopy,
  LuExternalLink as IconExternalLink,
  LuChevronRight as IconChevronRight,
  LuChevronLeft as IconChevronLeft,
  LuChevronDown as IconChevronDown,
  LuChevronUp as IconChevronUp,
  LuScissors as IconScissors,
  LuCpu as IconCpu,
  LuFilter as IconFilter,
  LuLock as IconLock,
  LuMail as IconMail,
  LuUser as IconUser,
  LuLogOut as IconLogOut,
  LuSparkles as IconSparkles,
  LuLoaderCircle as IconLoader,
  LuArrowRight as IconArrowRight,
  LuArrowUpRight as IconArrowUpRight,
  LuDownload as IconDownload,
  LuPlus as IconPlus,
  LuTrash2 as IconTrash,
  LuShield as IconShield,
  LuFileCheck as IconFileCheck,
  LuHash as IconHash,
  LuBookmark as IconBookmark,
  LuFileSpreadsheet as IconFileSpreadsheet,
  LuFileCode as IconFileCode,
  LuKey as IconKey,
  LuGlobe as IconGlobe,
  LuDollarSign as IconDollar,
  LuZap as IconZap,
  LuSlidersHorizontal as IconSliders,
};
